import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./provider/UserProvider";
import { DonationProvider } from "./provider/DonationProvider";
import AuthProvider from "./provider/AuthProvider";
import { BankCardProvider } from "./provider/BankCardProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <ToastContainer />
        <AuthProvider>
          <UserProvider>
            <DonationProvider>
              {" "}
              <BankCardProvider>{children}</BankCardProvider>
            </DonationProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
