import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./provider/UserProvider";
import { DonationProvider } from "./provider/DonationProvider";
import { ToastContainer } from "react-toastify";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import AuthProvider from "./provider/AuthProvider";
import { BankCardProvider } from "./provider/BankCardProvider";
import { ProfileProvider } from "./provider/ProfileProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <ToastContainer />
        <AuthProvider>
          <NuqsAdapter>
            <UserProvider>
              <BankCardProvider>
                <DonationProvider> {children}</DonationProvider>
              </BankCardProvider>
            </UserProvider>
          </NuqsAdapter>
        </AuthProvider>
      </body>
    </html>
  );
}
